import type { SupportedType } from '../types';

export const typeOrder: SupportedType[] = [
  'package',
  'domain',
  'dataElement',
  'messageClass',
  'structure',
  'table',
  'appendStructure',
  'tableType',
  'ddl',
  'scalarFunction',
  'functionGroup',
  'functionInclude',
  'functionModule',
  'interface',
  'class',
  'scalarFunctionImplementation',
  'program',
  'transformation',
  'serviceDefinition',
  'serviceBinding',
  'metadataExtension',
  'behaviorDefinition',
  'behaviorImplementation',
  'enhancement',
];
