export function usage(): string {
  return [
    'ADT Backup/Restore',
    '',
    'Commands:',
    '  backup  --objects <type:name[,type:name]> [--output file] [--destination name] [--env file] [--auth-root path]',
    '  backup  --package <name> [--output file] [--destination name] [--env file] [--auth-root path]',
    '  restore --input <file> [--mode create|update|upsert] [--activate] [--no-activate-on-create] [--no-activate-on-update] [--force] [--strict] [--dangerous] [--transport <request>] [--software-component <name>] [--destination name] [--env file] [--auth-root path]',
    '  diff    --input <file> --object <type:name> [--destination name] [--env file] [--auth-root path]',
    '  diff    --input <file> --all [--show-ok] [--destination name] [--env file] [--auth-root path]',
    '  verify  --input <file> [--format text|json] [--strict] [--destination name] [--env file] [--auth-root path]',
    '  validate --input <file> [--object <type:name>]',
    '  extract --input <file> --object <type:name> --out <file>',
    '  patch   --input <file> --object <type:name> --file <file> [--output file]',
    '  list    --input <file> [--format text|json] [--flat] [--deps]',
    '  --log-file <path> (write console output to a file)',
    '  --debug-adt (enable ADT/connection logs even in verify)',
    '  -vv/-vvv for verbose logging',
    '',
    'Examples:',
    '  adt-backup backup --objects class:ZCL_TEST,view:ZV_TEST --output backup.yaml --destination TRIAL',
    '  adt-backup backup --package ZPKG_TEST --output backup.yaml --destination TRIAL',
    '  adt-backup diff --input backup.yaml --object class:ZCL_TEST --destination TRIAL',
    '  adt-backup restore --input backup.yaml --mode upsert --activate --destination TRIAL',
    '  adt-backup validate --input backup.yaml',
    '  adt-backup validate --input backup.yaml --object class:ZCL_TEST',
    '  adt-backup verify --input backup.yaml --destination TRIAL',
    '  adt-backup extract --input backup.yaml --object class:ZCL_TEST --out ZCL_TEST.abap',
    '  adt-backup patch --input backup.yaml --object class:ZCL_TEST --file ZCL_TEST.abap',
    '  adt-backup list --input backup.yaml',
    '  adt-backup list --input backup.yaml --flat',
    '',
    'Object type examples:',
    '  class:ZCL_TEST',
    '  interface:ZIF_TEST',
    '  program:ZREP_TEST',
    '  view:ZV_TEST',
    '  domain:ZDOM_TEST',
    '  dataElement:ZDE_TEST',
    '  structure:ZST_TEST',
    '  table:ZT_TEST',
    '  tableType:ZTT_TEST',
    '  functionGroup:ZFG_TEST',
    '  functionModule:ZFG_TEST|ZFM_TEST',
    '  serviceDefinition:Z_I_SRV_DEF',
    '  metadataExtension:Z_I_SRV_EXT',
    '  behaviorDefinition:Z_I_BDEF',
  ].join('\n');
}
